# Generated by Django 4.2.7 on 2023-11-25 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Grupa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwota', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('idKlienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grupa.grupa')),
            ],
        ),
    ]
