# Generated by Django 4.2.7 on 2023-11-27 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Portfel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaTransakcji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kwota', models.IntegerField()),
                ('DataTransakcji', models.DateTimeField()),
                ('Typ', models.CharField(max_length=100)),
                ('ID_Portfela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfel.portfel')),
            ],
        ),
    ]
